FROM golang:latest

RUN mkdir -p /go/src/github.com/evdatsion/tools/tm-monitor
WORKDIR /go/src/github.com/evdatsion/tools/tm-monitor

COPY Makefile /go/src/github.com/evdatsion/tools/tm-monitor/

RUN make tools

COPY . /go/src/github.com/evdatsion/tools/tm-monitor

