FROM golang:latest

RUN mkdir -p /go/src/github.com/libonomy/aphelion-staking/tools/tm-bench
WORKDIR /go/src/github.com/libonomy/aphelion-staking/tools/tm-bench

COPY Makefile /go/src/github.com/libonomy/aphelion-staking/tools/tm-bench/

RUN make get_tools

COPY . /go/src/github.com/libonomy/aphelion-staking/tools/tm-bench

